### PR TITLE
Fix `nearby_tile_same_grf`, `nearby_tile_other_grf` and `nearby_tile_original_gfx`, they all compared to wrong constants

### PR DESCRIPTION
**Pull request by ahyangyi**
…original_gfx`, they all compared to wrong constants

### CODE REVIEW

**Comment by ahyangyi** [comment]
Relevant grfspec page:

https://newgrf-specs.tt-wiki.net/wiki/VariationalAction2/Stations

**Comment by ahyangyi** [comment]
Broken test is false alarm, should be fixed by #331...

**Comment by LordAro** [comment]
I think it would be less confusing to reorder the definitions so that the numbers are still 0, 1, 2

**Comment by ahyangyi** [comment]
I wanted to begin with a minimal delta, but the new order does make sense.

**Review by glx22 — APPROVED** [review]

**Pull request merged**
