### PR TITLE
Add boolean constants

### PR DESCRIPTION
**Pull request by spnda**
I'm not sure if this is already a thing, but I don't think it is.
I feel like this is a neat addition but maybe there should be some checking that these are correctly used? They just expand to `0` and `1` respectively.

### CODE REVIEW

**Comment by Yexo** [comment]
Do you have a particular use-case in mind for this?

**Comment by spnda** [comment]
For example, the `dual-headed` for trains expects a 0 or 1, so false or true.

**Comment by Yexo** [comment]
Fair enough, there are several other `vehicle_is_*` variables that are essentially bools. Then again, they're currently all documented as `0 | 1`. I see advantages in introducing a boolean type, but I'd rather do that properly instead of relying on integer values 0/1 disguising themselves as boolean.

That'd be a different approach than this PR is taking: the nml AST already has a Boolean type. Make use of that for `true` and `false` and then type-check all expressions including in switch-blocks to make sure those constants aren't mis-used.

**Comment by frosch123** [comment]
Defining "true" as 0, and "false" as 1, is asking for disaster.

**Comment by spnda** [comment]
> 
> 
> Fair enough, there are several other `vehicle_is_*` variables that are essentially bools. Then again, they're currently all documented as `0 | 1`. I see advantages in introducing a boolean type, but I'd rather do that properly instead of relying on integer values 0/1 disguising themselves as boolean.
> 
> That'd be a different approach than this PR is taking: the nml AST already has a Boolean type. Make use of that for `true` and `false` and then type-check all expressions including in switch-blocks to make sure those constants aren't mis-used.
Ok, I'll look into that.

> Defining "true" as 0, and "false" as 1, is asking for disaster.
ohh... oops

**Comment by andythenorth** [comment]
Odd timing, I am looking at a case where True and False as constants might be useful.  

Using True and False for return values from a procedure might be more readable than the current 1 and 0 I'm using.

Not sure it's essential, and I could add them in my python compile as constants if I wanted.  I didn't do that so eh :)

**Comment by spnda** [comment]
nevermind

**Pull request closed without merging**
