### PR TITLE
Update: changelog for 0.6.0

### PR DESCRIPTION
**Pull request by frosch123**
blocked by #173

### CODE REVIEW

**Comment by glx22** [comment]
Waiting on #212 or #220 ?

**Comment by 2TallTyler** [comment]
For what it's worth, I plan on using the `profit` callback in my new industry set, once these issues are resolved. So it's not just fixing something nobody uses. 😃

**Comment by andythenorth** [comment]
> blocked by #173

#173 merged 23rd May

**Comment by andythenorth** [comment]
Additions since March 3rd:

Changes
- add constants GROUNDSPRITE_GRASS, GROUNDSPRITE_DESERT_2_2, GROUNDSPRITE_GRASS_1_3, GROUNDSPRITE_GRASS_2_3, GROUNDSPRITE_GRASS_3_3
- add builtin functions for round() and sqrt()
- warn when a deprecated constant is used
- progress display shows input filename when reading files
- improve error message when invalid features are used
- add plural form 14 for Romanian
- do not check plural forms of translations
- no longer accept iso-codes as grflangid (removes undocumented feature)
- add variable for 'town_index' (var 0x41)

Fixes
- town_euclidean_dist was returning incorrect value
- rename MAP_TYPE_RECTANGULAR to MAP_TYPE_SQUARE
- LZ77 fallback is not compatible with Python 3.9
- define PY_SSIZE_T_CLEAN in _lz77.c for Python 3.10+ compatibility
- access to persistent-storage of towns was broken
- use most likely defined position when reporting error

**Comment by glx22** [comment]
LZ77 fixes can be merged as 3.9+ I think

**Comment by andythenorth** [comment]
> LZ77 fixes can be merged as 3.9+ I think

Done

**Comment by andythenorth** [comment]
This PR replaced by https://github.com/OpenTTD/nml/pull/232

**Pull request closed without merging**
