### PR TITLE
Fix: Allow access to towns as parent object

### PR DESCRIPTION
**Pull request by planetmaker**
So it needs some generic featureID used as parent.

Generally the features probably should be referenced via a symbolic name than their numeric ID in the code or this will fall onto our feet when a new feature is introduced. But that is a separate PR outside the scope of this.

And... I don't understand why this is not an update to the existing PR. Stupid github https://github.com/OpenTTD/nml/pull/26

### CODE REVIEW

**Comment by PeterN** [comment]
I think that separate PR should happen before this, to be honest.

**Comment by frosch123** [comment]
Alternative solution:
https://gist.github.com/frosch123/fb62db8e6a65c0de1614ad1f663f1827

It uses a text instead of a (wrong) number.
Towns are accepted by feature_name, but not by parse_feature.
Removes the references to feature 8, which were likely means to be "towns".

**Comment by glx22** [comment]
Since checks are enabled, a rebase to master is required to include workflow file.

**Comment by LordAro** [comment]
No change in a while. Gonna close this

**Pull request closed without merging**
