### PR TITLE
Industries: support 16 cargos in / 16 cargos out

### PR DESCRIPTION
**Pull request by andythenorth**
Currently using peter1138's rebase.

Spec documented in the OpenTTD PR https://github.com/OpenTTD/OpenTTD/pull/6867

Still WIP, known issues:

- won't compile grfs using prod. cb version 0 or 1, e.g. https://github.com/andythenorth/firs
- nml examples incomplete
- new features not fully tested

### CODE REVIEW

**Comment by TrueBrain** [comment]
Instead of a label 'draft', you can nowedays also make a Draft Pull Request in GitHub. Just you cannot convert an existing PR to a Draft PR :D

**Comment by PeterN** [comment]
Is this ready for merge?

**Comment by nielsmh** [comment]
I think @andythenorth talked about the old production cb syntax no longer working. I don't think that was fixed yet.

**Comment by planetmaker** [comment]
I'd like to encourage you again to just replace the old production syntax by this new one and not carry a bag of backward compatible stuff around. For backward compatibility I shall make releases for some time without such change.

**Comment by nielsmh** [comment]
I made another PR to this PR branch, removing some deprecated industry properties: https://github.com/PeterN/nml/pull/3

Apart from taking out the deprecated parts, this needs some better error reporting (if possible) of the old syntax, a migration guide, possibly better examples, and also support for 16 accepts for town houses.

**Comment by andythenorth** [comment]
invalid_sprite_16_cargos

**Comment by andythenorth** [comment]
FIRS branch that compiles with this and works as expected: https://github.com/andythenorth/firs/commits/v4-development-track

* new industry cargo_types prop
* produce block new format
* cb 37 new format and new flag
* new tile flag

**Pull request merged**
